name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.1, 8.0 ]
        laravel: [ "^10.0", "^9.0", "^8.0" ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        exclude:
          - laravel: "^10.0"
            php: 8.0

    name: Laravel ${{ matrix.laravel }} (${{ matrix.php }}) - ${{ matrix.dependency-version }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: l-${{ matrix.laravel }}-p-${{ matrix.php }}-${{ hashFiles('composer.json') }}
    - name: install php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
        coverage: none
    - name: Install Dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "nesbot/carbon:^2.63" --dev --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
    - name: Execute tests (Unit and Feature tests) via Pest
      run: vendor/bin/pest
